---
- name: Cloner les dépôts du projet DevOps
  hosts: all
  gather_facts: no
  tasks:

    - name: Créer le dossier ~/Projet s'il n'existe pas
      file:
        path: "{{ ansible_env.HOME }}/Projet"
        state: directory
        mode: '0755'

    - name: Cloner le dépôt GitHub (infra)
      git:
        repo: https://github.com/Bloraze/Dossier-DevOps.git
        dest: "{{ ansible_env.HOME }}/Projet/Dossier-DevOps"
        clone: yes
        update: yes

    - name: Cloner le dépôt GitLab (CI/CD)
      git:
        repo: https://gitlab.com/Bloraze/CI-CD.git
        dest: "{{ ansible_env.HOME }}/Projet/CI-CD"
        clone: yes
        update: yes


