all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/key.pem  # 🔐 Chemin de ta clé SSH
  children:
    nginx:
      hosts:
        nginx-main:
          ansible_host: 35.181.160.3
        nginx-replica:
          ansible_host: 51.44.161.198

    monitoring:
      hosts:
        prom-graf:
          ansible_host: 15.237.251.46
