apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-main
  template:
    metadata:
      labels:
        app: nginx-main
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-main-service
spec:
  selector:
    app: nginx-main
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
